apiVersion: batch/v1
kind: CronJob
metadata:
  name: article-generation
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: acr-reco-secret
          containers:
          - name: article-generation-container
            image: amavlarecommendation.azurecr.io/articles:article-generation-latest
            imagePullPolicy: Always
          restartPolicy: OnFailure

